### ISSUE TITLE
Add support for Dimensions Badges

### ISSUE THREAD

**Issue by bradspry** [Islandora/islandora_badges#28]
Documentation:
https://badge.dimensions.ai

**Comment by bondjimbond** [comment]
@bradspry Please use JIRA to report these issues/requests... Badges is owned by Islandora, so everything for it should be tracked in JIRA. 

@manez I think issues are supposed to be turned off for Islandora repos; is that correct? I don't have access to the settings to change this.

Also @bradspry - it was decided a while back that most if not all future Badges would probably not end up in the core repository, and should instead live as contrib modules. There is a Dimensions badge available: https://github.com/bondjimbond/islandora_dimensions

**Comment by manez** [comment]
@bradspry @bondjimbond That's correct, we don't use issues for Islandora 7.x stuff. JIRA's the venue (it's different in Islandora 8, where we are indeed using GitHub for everything) This one must have been turned on by accident or overlooked. I'll update the settings once this issue is resolved.
